# Generated by Django 5.2.17 on 2026-08-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoInstancia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_exibicao",
                    models.CharField(
                        default="Nutri White-Label",
                        max_length=120,
                        verbose_name="Nome da empresa",
                    ),
                ),
                (
                    "logotipo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "cor_primaria",
                    models.CharField(
                        default="#198754",
                        max_length=7,
                        verbose_name="Cor primária (hex)",
                    ),
                ),
                (
                    "ano_corte_ingredientes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Se preenchido, as listas de ingredientes só exibem os criados a partir deste ano (comportamento da instância Nutri Jr: 2024 — BR-017/D-010).",
                        null=True,
                        verbose_name="Ano de corte de ingredientes",
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Configuração da instância",
                "verbose_name_plural": "Configuração da instância",
            },
        ),
    ]
