# Generated by Django 5.2.17 on 2026-08-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoinstancia',
            name='logotipo',
        ),
        migrations.AddField(
            model_name='configuracaoinstancia',
            name='logotipo_atualizado_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoinstancia',
            name='logotipo_dados',
            field=models.BinaryField(blank=True, null=True, verbose_name='Logotipo (conteúdo)'),
        ),
        migrations.AddField(
            model_name='configuracaoinstancia',
            name='logotipo_tipo',
            field=models.CharField(blank=True, editable=False, max_length=40, verbose_name='Logotipo (tipo)'),
        ),
    ]
